### PR TITLE
This should work but vignettes fail

### PR DESCRIPTION
**Pull request by muschellij2**
I don't know why but the vignettes say they take over 10 minutes to run but that's not the case on my machine.

### CODE REVIEW

**Comment by zhenkewu** [comment]
@muschellij2 THe vignettes build fine on my mac too. Maybe the settings of JAGS are different on the travis machines. Maybe we can look at where the build of vignettes is wrong. It currently says (10m0s no output...)

**Comment by zhenkewu** [comment]
@muschellij2 I updated baker yesterday. Not lucky in getting the vignette working. Should we set wait time to longer? Or should we bypass vignette building?

**Comment by muschellij2** [comment]
Sorry - I don't have the time right now to work on this.  You may want to
use travis_wait and run R CMD check in the travis file yourself to see if
that's the issue.

John

**Comment by zhenkewu** [comment]
Ok. Will do. I'm mimicking here:
https://github.com/ANTsX/ANTsRCore/blob/master/.travis.yml

Zhenke

**Pull request merged**
